#!/usr/bin/env bash

#AWS EC2: security groups
if [ -s "${TMP}/${AWS_SECURITY_GROUPS}_full.json" ]
then
  inf ""
  inf "${MAGENTA}Checking if security group ${BROWN}${SECURITY_GROUP_EC2_NAME}${MAGENTA} exists"
  SECURITY_GROUP_ID=$(jq -r --arg security_group_name ${SECURITY_GROUP_EC2_NAME} '.SecurityGroups[] | select(.GroupName == $security_group_name) | .GroupId' "${TMP}/${AWS_SECURITY_GROUPS}_full.json")
  if [ ! -z ${SECURITY_GROUP_ID} ]
  then
    warn "  Security group: ${BROWN}${SECURITY_GROUP_EC2_NAME}${WINE} already exists"
    SECURITY_GROUP_EXISTS="yes"
  else
    aws_ec2_security_group_create "${SECURITY_GROUP_EC2_NAME}"
  fi
fi
#AWS EC2: security groups
END_DEPLOY_TIME=$(date +%s.%4N)
DEPLOY_TIME=$(echo "scale=4; x=(${END_DEPLOY_TIME} - ${START_DEPLOY_TIME}); if(x<1) print 0; x" | bc)

START_DEPLOY_INSTANCE_TIME=$(date +%s.%4N)
inf ""
inf "${MAGENTA}Creating new instance based on AMI: ${YELLOW}${AWS_AMI_ID}${MAGENTA} and instance_type ${LIME}${AWS_INSTANCE_TYPE}${MAGENTA} in ${DARK_GREEN}${SECURITY_GROUP_ID}${MAGENTA} security group ID"
aws ec2 run-instances ${AWS_PROFILE_USE_CHECK} --image-id ${AWS_AMI_ID} --count 1 --instance-type ${AWS_INSTANCE_TYPE} --key-name ${KEY_NAME} --subnet-id ${SUBNET_ID} --security-group-ids ${SECURITY_GROUP_ID} > "${TMP}/${AWS_INSTANCES_DETAILS}_run_full.json" 2>&1 &
while [[ -n $(jobs -r) ]]
do
  for NUMBER in {1..100}
  do
    sleep 0.15
    ProgressBar ${NUMBER} 100
  done
  printf '\n'
done
AWS_INSTANCE_DETAILS_IP=$(jq -r ".Instances[].PrivateIpAddress" "${TMP}/${AWS_INSTANCES_DETAILS}_run_full.json")
AWS_INSTANCE_DETAILS_ID=$(jq -r ".Instances[].InstanceId" "${TMP}/${AWS_INSTANCES_DETAILS}_run_full.json")
sleep 2
#ToDo: aws ${AWS_PROFILE_USE_CHECK} ec2 modify-instance-attribute --instance-id ${AWS_INSTANCE_DETAILS_ID} --block-device-mappings "[{\"DeviceName\": \"/dev/sda1\",\"Ebs\":{\"DeleteOnTermination\":true}}]"
END_DEPLOY_INSTANCE_TIME=$(date +%s.%4N)
AWS_START_VM_TIME=$(echo "scale=4; x=(${END_DEPLOY_INSTANCE_TIME} - ${START_DEPLOY_INSTANCE_TIME}); if(x<1) print 0; x" | bc)
START_READY_INSTANCE_TIME=$(date +%s.%4N)
inf "  Instance: ${YELLOW}${AWS_INSTANCE_DETAILS_ID}${CYAN} with IP: ${LIME}${AWS_INSTANCE_DETAILS_IP}${CYAN} has just been created"
inf "    ${MAGENTA}Checking if ${YELLOW}${DEFAULT_INET_IP}${MAGENTA} may log in by ssh to instance: ${YELLOW}${AWS_INSTANCE_DETAILS_ID}"
aws ec2 ${AWS_PROFILE_USE_CHECK} describe-security-groups > "${TMP}/${AWS_SECURITY_GROUPS}_full.json"
SECURITY_GROUP_INGRESS_FOR_LOCAL_IP=$(jq -r --arg default_inet_ip ${DEFAULT_INET_IP} '.SecurityGroups[].IpPermissions[].IpRanges[] | select(.CidrIp | startswith($default_inet_ip)) | .CidrIp' "${TMP}/${AWS_SECURITY_GROUPS}_full.json")
if [ -z ${SECURITY_GROUP_INGRESS_FOR_LOCAL_IP} ]
then
  aws_security_group_ingress_add ${SECURITY_GROUP_ID} "${DEFAULT_INET_IP}/32"
fi
if [ ! -z ${EXTERNAL_INET_IP} ]
then
  if [[ ${EXTERNAL_INET_IP} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
  then
    #inf "      Adding external/public IP address: ${LIME}${EXTERNAL_INET_IP}${CYAN} to allow ssh to instance(s)"
    aws_security_group_ingress_add ${SECURITY_GROUP_ID} "${EXTERNAL_INET_IP}/32"
  fi
fi

associating_instance-to-profile ${AWS_INSTANCE_DETAILS_ID} "${AWS_EC2_INSTANCES_PROFILE}"
AWS_INSTANCE_PROFILES_ASSOCIATION_ID=$(jq -r '.IamInstanceProfileAssociation.AssociationId' "${TMP}/${AWS_INSTANCE_PROFILES_ASSOCIATIONS}_${AWS_INSTANCE_DETAILS_ID}_profile_association.json")
inf "    ${MAGENTA}Checking if instance: ${YELLOW}${AWS_INSTANCE_DETAILS_ID}${MAGENTA} is already up..."
while ! $(timeout --preserve-status -s 9 -k 6 4 ssh -o "StrictHostKeyChecking no" ${DEPLOY_USER}@${AWS_INSTANCE_DETAILS_IP} 'exit' >> "${LOG}/${AWS_INSTANCES_DETAILS}_ssh_testing.log" 2>&1 ) >> "${LOG}/${AWS_INSTANCES_DETAILS}_ssh_testing.log" 2>&1 
do
  for NUMBER in {1..100}
  do
    sleep 0.25
    ProgressBar ${NUMBER} 100
  done
  printf '\n'
done
inf "      Instance ${YELLOW}${AWS_INSTANCE_DETAILS_ID}${CYAN} is up"

END_READY_INSTANCE_TIME=$(date +%s.%4N)
AWS_READY_VM_TIME=$(echo "scale=4; x=(${END_READY_INSTANCE_TIME} - ${START_READY_INSTANCE_TIME}); if(x<1) print 0; x" | bc)

aws ec2 describe-instances  ${AWS_PROFILE_USE_CHECK}  --instance-ids ${AWS_INSTANCE_DETAILS_ID} > "${TMP}/${AWS_INSTANCES_DETAILS}_full.json"
AWS_VOLUME_ID=$(jq -r '.Reservations[].Instances[].BlockDeviceMappings[].Ebs.VolumeId' "${TMP}/${AWS_INSTANCES_DETAILS}_full.json")
inf "        Cloning ${BROWN}${AWS_REPO_ADDRESS}"
ssh -o "StrictHostKeyChecking no" -n -f ${DEPLOY_USER}@${AWS_INSTANCE_DETAILS_IP} "sh -c 'git clone ${AWS_REPO_ADDRESS} > /dev/null 2>&1'"
ERROR_CODE="$?"

###################
if [[ ${RUN_SCRIPT} == yes ]]
then
  REPO=""
  REPO_BRANCH=""
  SCRIPT_NAME=""
  SCRIPT_PARAMETERS=""
  aws_run_EC2_code ${REPO} ${REPO_BRANCH} ${SCRIPT_NAME} "${SCRIPT_PARAMETERS}"
  aws_instance_removal ${AWS_INSTANCE_DETAILS_ID}
fi
###################
