#!/usr/bin/env bash  

if [[ ${VERBOSE} == yes ]]
then
  debug "${YELLOW}[ ${LIME}$(echo $(caller | awk '{print $2}') | awk -F\/ '{print $NF}') ${YELLOW}calls (in line: ${LIME}$(caller | awk '{print $1}')${YELLOW}) ${LIME}$(echo ${BASH_SOURCE} | awk -F\/ '{print $NF}')${YELLOW} ]"
fi

IFS=${ORIGIFS}

SLACK_PAYLOAD="
{\\\"channel\\\": \\\"${SLACK_CHANNEL_AWS}\\\"
  , \\\"username\\\": \\\"${USER}, (${YOUR_IP})\\\"
  , \\\"icon_emoji\\\": \\\":musical_score:\\\"
  , \\\"attachments\\\":
    [
      {
        \\\"fallback\\\": \\\"Lambda function: ${AWS_LAMBDA_FUNCTION_NAME} has just been created\\\",
        \\\"color\\\": \\\"good\\\",
        \\\"title\\\": \\\"AWS Lambda notification\\\",
        \\\"text\\\": \\\"AWS Lambda function: *${AWS_LAMBDA_FUNCTION_NAME}* has been deployed\\\"
      }
    ]
, \\\"token\\\": \\\"${SLACK_TOKEN}\\\"
}" 

echo "curl ${SLACK_PROXY_CONTROL[*]} -v -X POST --data \"${SLACK_PAYLOAD}\" ${SLACK_WEB_HOOK}" > "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}_slack_lambda.in"
source "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}_slack_lambda.in" > "${LOG}/${AWS_LAMBDA_FUNCTION_NAME}_slack_lambda.log" 2>&1
