#!/usr/bin/env bash

if [[ ${VERBOSE} == yes ]]
then
  debug "${YELLOW}[ ${LIME}$(echo $(caller | awk '{print $2}') | awk -F\/ '{print $NF}') ${YELLOW}calls (in line: ${LIME}$(caller | awk '{print $1}')${YELLOW}) ${LIME}$(echo ${BASH_SOURCE} | awk -F\/ '{print $NF}') ${YELLOW} ]"
fi

if [ -z ${o} ]
then
  export VAR="${HOME}/var"
  mkdir -p ${VAR}
else
  export VAR=$(readlink -f ${o})
  mkdir -p ${VAR} > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    error "I have no permissions to create OUTPUT directory here"
    exit 1
  fi
fi

if [ -z ${TMP} ]
then
  export TMP="${VAR}/tmp-${SCRIPT_NAME}_${CURRENT_TIMESTAMP}"
  mkdir -p ${TMP}
fi

if [ -z ${LOG} ]
then
  export LOG="${VAR}/log-${SCRIPT_NAME}_${CURRENT_TIMESTAMP}"
  mkdir -p ${LOG}
fi
