#!/usr/bin/env bash

if [[ ${VERBOSE} == yes ]]
then
  debug "${YELLOW}[ ${LIME}$(echo $(caller | awk '{print $2}') | awk -F\/ '{print $NF}') ${YELLOW}calls (in line: ${LIME}$(caller | awk '{print $1}')${YELLOW}) ${LIME}$(echo ${BASH_SOURCE} | awk -F\/ '{print $NF}') ${YELLOW} ]"
fi

if [ -z ${o} ]
then
  if [ -z ${TERADATA_VAR} ]
  then
    export VAR="${HOME}/var"
    mkdir -p ${VAR}
    export TERADATA_VAR=${VAR}
  else
    export VAR=${TERADATA_VAR}
    mkdir -p ${VAR}
  fi
else
  export VAR=$(readlink -f ${o})
  export TERADATA_VAR=${VAR}
  mkdir -p ${VAR} > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    error "I have no permissions to create OUTPUT directory here"
    exit 1
  fi
fi

if [ -z ${TMP} ]
then
  export TMP="${VAR}/tmp-${SCRIPT_NAME}_${CURRENT_TIMESTAMP}"
  export TDDDL_TMP=${TMP}
  mkdir -p ${TMP}
  if [ -z ${TERADATA_TMP} ]
  then
    export TERADATA_TMP=${TMP}
  fi
fi

if [ -z ${LOG} ]
then
  export LOG="${VAR}/log-${SCRIPT_NAME}_${CURRENT_TIMESTAMP}"
  export TDDDL_LOG=${LOG}
  mkdir -p ${LOG}/TPT/checkpoint
  if [ -z ${TERADATA_LOG} ]
  then
    export TERADATA_LOG=${LOG}
  fi
fi
